name: flutter_gps_manager
description: "Flutter plugin to handle Gps state"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.navideck.flutter_gps_manager
        pluginClass: FlutterGpsManagerPlugin
